# Generated by Django 4.1.7 on 2023-07-04 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('RTO_days', models.IntegerField(default=0)),
                ('position', models.CharField(choices=[('CS', 'Coffee Specialist'), ('SS', 'Stock Specialist'), ('TL', 'Team Lead'), ('MG', 'Manager'), ('CB', 'Coffee Bard')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RTO', 'Requested Time Off'), ('PRF', 'Preferred shift')], max_length=3)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.person')),
            ],
        ),
    ]
