# Generated by Django 4.1.7 on 2023-07-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
