# Generated by Django 4.1.7 on 2023-07-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
