# Generated by Django 4.1.7 on 2023-07-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_event_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
