# Generated by Django 4.1.7 on 2023-07-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_boutique_event_boutique_person_boutique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
