# Generated by Django 4.1.7 on 2023-07-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_alter_boutique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
