# Generated by Django 4.1.7 on 2023-07-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_event_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('RTO', 'Requested Time Off'), ('PRF', 'Preferred shift'), ('VAC', 'Vacation'), ('SWP', 'Swap Shift')], max_length=3),
        ),
    ]
