# Generated by Django 4.1.7 on 2023-07-29 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_remove_event_time_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.boutique'),
        ),
        migrations.AlterField(
            model_name='event',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.person'),
        ),
        migrations.CreateModel(
            name='ShiftCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('covering_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covering_person', to='scheduler.person')),
                ('original_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_person', to='scheduler.person')),
            ],
        ),
    ]
