# Generated by Django 4.1.7 on 2023-07-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_alter_event_boutique_alter_event_person_shiftcover'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftcover',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.boutique'),
        ),
        migrations.AddField(
            model_name='shiftcover',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
