# Generated by Django 4.1.7 on 2023-07-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_shiftcover_boutique_shiftcover_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('RTO', 'Requested Time Off'), ('PRF', 'Preferred shift'), ('VAC', 'Vacation'), ('SWP', 'Swap Shift'), ('OTH', 'Other')], max_length=3),
        ),
    ]
