# Generated by Django 4.1.7 on 2023-07-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied'), ('O', 'Other')], default='Pending', max_length=1),
        ),
    ]
