# Generated by Django 4.1.7 on 2023-08-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='MAX_RTO_CS_WEEKDAY',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boutique',
            name='MAX_RTO_CS_WEEKEND',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boutique',
            name='MAX_RTO_MG',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boutique',
            name='MAX_RTO_SPECIAL_EVENTS',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boutique',
            name='MAX_RTO_SS_WEEKDAY',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boutique',
            name='MAX_RTO_SS_WEEKEND',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boutique',
            name='MAX_RTO_TL_WEEKDAY',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boutique',
            name='MAX_RTO_TL_WEEKEND',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boutique',
            name='MAX_RTO_TOTAL_WEEKDAY',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boutique',
            name='MAX_RTO_TOTAL_WEEKEND',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
